{application,web_conbee_test,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{web_conbee_test_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[conbee,conbee_init,lgh,lgh_handler,lgh_init,
                        lib_conbee,lights,lumi_sensor_magnet_aq2,
                        lumi_sensor_motion_aq2,lumi_weather,
                        no_matching_route_handler,sensors,
                        tradfri_bulb_e27_cws_806lm,tradfri_bulb_e27_ww_806lm,
                        tradfri_control_outlet,varmdo_mm,web_conbee,
                        web_conbee_test_app,web_conbee_test_sup]},
              {licenses,["Apache 2.0"]},
              {links,[]}]}.
